### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by dvershinin** [torsilviu/ngx_mod_status#1]
Please update the README with information on what the module actually does and how it's useful…

**Comment by codebytes5** [comment]
@dvershinin this plugin is the alternative to apache mod_status module for nginx

**Comment by dvershinin** [comment]
Just saying it is alternative to a module from another web server is like saying nothing. Could you include in the README what it really does instead of referring elsewhere. Perhaps:

> The NGINX Status module, much like Apache’s Status module, provides server administrators with real-time performance metrics in a user-friendly HTML format, including an option for auto-refresh and a machine-readable summary of the server’s current state.

**Comment by codebytes5** [comment]
Yeah ok, it provides the information about the connections on the server taken from the log phase which is later written to the log files by nginx. It displays the info in a table similar to the one provided by apache in their plugin. There's also an epoll plugin for linux provided which catches lingering conections that don't get closed by nginx.

Hope that clears some things, will update the readme on future patches, post here if there's compiling isues or other for newer versions of nginx and I'll try to patch them.
